service: static-site-mailer

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-1
  stage: prod
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource: ["*"]
  environment:
    AllowOrigin: 'chris.dickinson.ch'

# you can define service wide environment variables here
#  environment:
#    variable1: value1

functions:
  staticSiteMailer:
    handler: handler.staticSiteMailer
    events:
      - http:
          method: post
          path: static-site-mailer
          cors: true